# =============================================================================
# 📚 MkDocs Configuration - QFrame Documentation Vivante
# =============================================================================

site_name: "QFrame - Framework Quantitatif Professionnel"
site_description: "Documentation complète du framework QFrame pour la recherche quantitative et le trading algorithmique"
site_author: "Quantitative Research Team"
site_url: "https://qframe.readthedocs.io"

# =============================================================================
# 📁 Repository & Navigation
# =============================================================================

repo_name: "1BoNoBo1/quant_framework_research"
repo_url: "https://github.com/1BoNoBo1/quant_framework_research"
edit_uri: "edit/main/docs/"

nav:
  - 🏠 Accueil: index.md
  - 🚀 Démarrage Rapide:
    - Installation: getting-started/installation.md
    - Premier Exemple: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - 🏗️ Architecture:
    - Vue d'Ensemble: architecture/overview.md
    - Dependency Injection: architecture/di-container.md
    - Configuration: architecture/configuration.md
    - Interfaces & Protocols: architecture/interfaces.md
  - 🧠 Stratégies de Trading:
    - Introduction: strategies/index.md
    - DMN LSTM Strategy: strategies/dmn-lstm.md
    - Mean Reversion: strategies/mean-reversion.md
    - Funding Arbitrage: strategies/funding-arbitrage.md
    - RL Alpha Generation: strategies/rl-alpha.md
  - 🔬 Feature Engineering:
    - Opérateurs Symboliques: features/symbolic-operators.md
    - Feature Processors: features/processors.md
    - Pipeline de Features: features/pipeline.md
  - 💼 Portfolio & Risk:
    - Portfolio Management: portfolio/management.md
    - Risk Assessment: portfolio/risk.md
    - Position Sizing: portfolio/sizing.md
  - 📊 Backtesting:
    - Engine de Backtesting: backtesting/engine.md
    - Métriques de Performance: backtesting/metrics.md
    - Validation Croisée: backtesting/validation.md
  - 🔬 Research Platform:
    - Vue d'Ensemble: research/overview.md
    - Data Lake: research/data-lake.md
    - Distributed Computing: research/distributed.md
    - MLOps Pipeline: research/mlops.md
  - 🖥️ Interface Utilisateur:
    - Dashboard Web: ui/dashboard.md
    - API REST: ui/api.md
    - CLI: ui/cli.md
  - 🛠️ Développement:
    - Guide du Contributeur: development/contributing.md
    - Tests: development/testing.md
    - CI/CD: development/cicd.md
  - 📖 API Reference: reference/
  - 📚 Exemples:
    - Exemples Complets: examples/index.md
    - Tutoriels: examples/tutorials.md
  - 🔗 Ressources:
    - Papiers de Recherche: resources/papers.md
    - Bibliographie: resources/bibliography.md
    - Glossaire: resources/glossary.md

# =============================================================================
# 🎨 Theme & Appearance
# =============================================================================

theme:
  name: material
  language: fr
  favicon: assets/favicon.ico
  logo: assets/logo.png

  # Material Design Features
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  # Color Palette
  palette:
    # Dark mode (default)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: "Passer en mode clair"

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: "Passer en mode sombre"

  # Custom CSS
  custom_dir: docs/assets/css

  # Typography
  font:
    text: Roboto
    code: Roboto Mono

# =============================================================================
# 🔌 Plugins Configuration
# =============================================================================

plugins:
  # Core Documentation seulement
  - search:
      lang:
        - en
        - fr

  # Macros et variables dynamiques
  - macros:
      modules:
        - docs.scripts.macros
      include_dir: docs/includes

# =============================================================================
# 📝 Markdown Extensions
# =============================================================================

markdown_extensions:
  # Python Markdown Core
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: "Lien permanent vers cette section"
      toc_depth: 3
  - tables
  - codehilite

  # PyMdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: 1BoNoBo1
      repo: quant_framework_research
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs/snippets
        - .
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# =============================================================================
# ⚡ Extra Configuration
# =============================================================================

extra:
  # Analytics (optionnel)
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, ""]
    feedback:
      title: "Cette page vous a-t-elle été utile ?"
      ratings:
        - icon: material/emoticon-happy-outline
          name: "Cette page m'a aidé"
          data: 1
          note: "Merci pour votre retour !"
        - icon: material/emoticon-sad-outline
          name: "Cette page peut être améliorée"
          data: 0
          note: "Merci, aidez-nous à améliorer cette page en utilisant notre formulaire de feedback."

  # Réseaux sociaux
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1BoNoBo1/quant_framework_research
      name: "QFrame sur GitHub"
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/qframe
      name: "QFrame sur PyPI"
    - icon: fontawesome/solid/paper-plane
      link: mailto:research@qframe.dev
      name: "Contact par email"

  # Versioning
  version:
    provider: mike
    default: latest

  # Variables globales pour macros
  project:
    name: "QFrame"
    version: "0.1.0"
    python_versions: ["3.11", "3.12", "3.13"]
    license: "MIT"

  # Configuration des features
  features:
    trading_live: true
    research_platform: true
    web_interface: true

# =============================================================================
# 📄 Extra Files
# =============================================================================

extra_css:
  - assets/css/extra.css
  - assets/css/code-annotations.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - assets/js/extra.js
  - assets/js/mathjax.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

# =============================================================================
# ⚙️ Development & Build
# =============================================================================

# Watch files for development
watch:
  - qframe/
  - docs/
  - mkdocs.yml

# Validation stricte (désactivée temporairement)
strict: false

# Configuration pour GitHub Pages
site_dir: site