# Feature Flags Configuration
# ===========================
# Gestion des fonctionnalités avec flags dynamiques

flags:
  # === FONCTIONNALITÉS CORE ===

  advanced_analytics:
    enabled: true
    description: "Activer les analytics avancées et métriques détaillées"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 100.0

  real_time_monitoring:
    enabled: true
    description: "Monitoring et alertes en temps réel"
    environments:
      - "staging"
      - "production"
    rollout_percentage: 100.0

  performance_optimization:
    enabled: true
    description: "Optimisations de performance et caching avancé"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 100.0

  # === FONCTIONNALITÉS STRATÉGIES ===

  experimental_strategies:
    enabled: true
    description: "Stratégies expérimentales en cours de développement"
    environments:
      - "development"
      - "testing"
    rollout_percentage: 100.0

  ml_strategies:
    enabled: true
    description: "Stratégies basées sur machine learning"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 80.0
    dependencies:
      - "advanced_analytics"

  arbitrage_strategies:
    enabled: false
    description: "Stratégies d'arbitrage cross-exchange"
    environments:
      - "development"
      - "staging"
    rollout_percentage: 50.0

  high_frequency_trading:
    enabled: false
    description: "Trading haute fréquence (nécessite infrastructure spécialisée)"
    environments:
      - "production"
    rollout_percentage: 0.0
    dependencies:
      - "performance_optimization"
      - "real_time_monitoring"

  # === FONCTIONNALITÉS RISQUE ===

  advanced_risk_management:
    enabled: true
    description: "Gestion des risques avancée avec ML"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 90.0
    dependencies:
      - "ml_strategies"

  portfolio_optimization:
    enabled: true
    description: "Optimisation de portfolio temps réel"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 75.0

  dynamic_hedging:
    enabled: false
    description: "Hedging dynamique automatique"
    environments:
      - "staging"
      - "production"
    rollout_percentage: 25.0
    dependencies:
      - "advanced_risk_management"

  # === FONCTIONNALITÉS DATA ===

  alternative_data:
    enabled: true
    description: "Sources de données alternatives (news, sentiment, etc.)"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 60.0

  real_time_data_streaming:
    enabled: true
    description: "Streaming de données en temps réel"
    environments:
      - "staging"
      - "production"
    rollout_percentage: 85.0

  data_quality_monitoring:
    enabled: true
    description: "Monitoring automatique de la qualité des données"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 100.0

  # === FONCTIONNALITÉS API ===

  api_rate_limiting:
    enabled: true
    description: "Rate limiting intelligent pour les APIs"
    environments:
      - "staging"
      - "production"
    rollout_percentage: 100.0

  api_caching:
    enabled: true
    description: "Cache intelligent pour les réponses API"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 90.0

  graphql_api:
    enabled: false
    description: "API GraphQL en plus de REST"
    environments:
      - "development"
    rollout_percentage: 30.0

  websocket_api:
    enabled: true
    description: "API WebSocket pour données temps réel"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 70.0

  # === FONCTIONNALITÉS UI/UX ===

  advanced_dashboard:
    enabled: true
    description: "Dashboard avancé avec visualisations interactives"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 80.0

  mobile_app:
    enabled: false
    description: "Application mobile native"
    environments:
      - "development"
    rollout_percentage: 0.0

  dark_mode:
    enabled: true
    description: "Mode sombre pour l'interface"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 100.0

  # === FONCTIONNALITÉS SÉCURITÉ ===

  advanced_authentication:
    enabled: true
    description: "Authentification avancée (2FA, SSO, etc.)"
    environments:
      - "staging"
      - "production"
    rollout_percentage: 100.0

  encryption_at_rest:
    enabled: true
    description: "Chiffrement des données au repos"
    environments:
      - "production"
    rollout_percentage: 100.0

  audit_logging:
    enabled: true
    description: "Logging d'audit complet"
    environments:
      - "staging"
      - "production"
    rollout_percentage: 100.0

  # === FONCTIONNALITÉS INTÉGRATION ===

  third_party_integrations:
    enabled: true
    description: "Intégrations avec services tiers"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 70.0

  webhook_notifications:
    enabled: true
    description: "Notifications via webhooks"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 85.0

  slack_integration:
    enabled: true
    description: "Intégration Slack pour alertes"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 90.0

  # === FONCTIONNALITÉS PERFORMANCE ===

  background_tasks:
    enabled: true
    description: "Tâches de fond asynchrones"
    environments:
      - "development"
      - "staging"
      - "production"
    rollout_percentage: 100.0

  distributed_computing:
    enabled: false
    description: "Calculs distribués sur cluster"
    environments:
      - "production"
    rollout_percentage: 20.0
    dependencies:
      - "performance_optimization"

  gpu_acceleration:
    enabled: false
    description: "Accélération GPU pour ML"
    environments:
      - "development"
      - "production"
    rollout_percentage: 10.0
    dependencies:
      - "ml_strategies"

  # === FONCTIONNALITÉS DÉVELOPPEMENT ===

  debug_endpoints:
    enabled: true
    description: "Endpoints de debug et diagnostics"
    environments:
      - "development"
      - "testing"
    rollout_percentage: 100.0

  hot_reload:
    enabled: true
    description: "Rechargement à chaud du code"
    environments:
      - "development"
    rollout_percentage: 100.0

  profiling:
    enabled: true
    description: "Profiling de performance"
    environments:
      - "development"
      - "staging"
    rollout_percentage: 100.0

  mock_services:
    enabled: true
    description: "Services mockés pour développement"
    environments:
      - "development"
      - "testing"
    rollout_percentage: 100.0

# Configuration globale des feature flags
global_config:
  # Vérification des dépendances
  check_dependencies: true

  # Logging des changements de flags
  log_flag_changes: true

  # Cache des évaluations de flags
  cache_evaluations: true
  cache_ttl: 300  # 5 minutes

  # Métriques sur l'utilisation des flags
  collect_metrics: true

  # Rollback automatique en cas d'erreur
  auto_rollback: true
  error_threshold: 0.05  # 5% d'erreur max